# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ddc627fdbecbfae5d6e4252a102934e98ad513439139148a4cb75d376110ae937453f163b60285eb27d68bdbcae598a861b6014e8822fea453c5108e1818fdd

test:
  secret_key_base: 9c99cfb00d0070ee0ce1329db21bec85cf26fbab4cbae3f0a55ec8c5cd946d5321e370636ce4d7f56f7c8a43cbc54645f2e5e7b3714b17e6cfb71a8c1b38f7f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
