languages = [
  "JavaScript",
  "Java",
  "Ruby",
  "C",
  "CSS",
  "PHP",
  "Python",
  "C++",
  "Objective-C",
  "C#",
  "Shell",
  "R",
  "CoffeeScript",
  "Go",
  "Perl",
  "Scala",
  "VimL",
  "Clojure",
  "Haskell",
  "Erlang",
  "Rust",
  "Swift"
]

languages.each do |lang|
  Language.create(name: lang)
end
[
  {
  "login": "121watts",
  "id": 7582765,
  "avatar_url": "https://avatars.githubusercontent.com/u/7582765?v=3",
  "html_url": "https://github.com/121watts",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 0,
  "C": 1,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 0,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 0
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "alanbsmith",
  "id": 4818182,
  "avatar_url": "https://avatars.githubusercontent.com/u/4818182?v=3",
  "html_url": "https://github.com/alanbsmith",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 1,
  "C": 0,
  "CSS": 0,
  "PHP": 1,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "allisonlarson",
  "id": 7552541,
  "avatar_url": "https://avatars.githubusercontent.com/u/7552541?v=3",
  "html_url": "https://github.com/allisonlarson",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 1,
  "C": 1,
  "CSS": 1,
  "PHP": 1,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "AndyDangerous",
  "id": 2694765,
  "avatar_url": "https://avatars.githubusercontent.com/u/2694765?v=3",
  "html_url": "https://github.com/AndyDangerous",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 0
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "BobGu",
  "id": 4348166,
  "avatar_url": "https://avatars.githubusercontent.com/u/4348166?v=3",
  "html_url": "https://github.com/BobGu",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 0,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 1,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 1,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 1
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "chadbrading",
  "id": 6863100,
  "avatar_url": "https://avatars.githubusercontent.com/u/6863100?v=3",
  "html_url": "https://github.com/chadbrading",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 0,
  "C": 1,
  "CSS": 0,
  "PHP": 1,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 1,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 1
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "coreyd303",
  "id": 6662565,
  "avatar_url": "https://avatars.githubusercontent.com/u/6662565?v=3",
  "html_url": "https://github.com/coreyd303",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 0,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 0,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "emilyadavis303",
  "id": 7103421,
  "avatar_url": "https://avatars.githubusercontent.com/u/7103421?v=3",
  "html_url": "https://github.com/emilyadavis303",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 1,
  "C": 1,
  "CSS": 0,
  "PHP": 1,
  "Python": 0,
  "C++": 1,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 1
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "ericfransen",
  "id": 5271281,
  "avatar_url": "https://avatars.githubusercontent.com/u/5271281?v=3",
  "html_url": "https://github.com/ericfransen",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 0,
  "C++": 1,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 0,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "GusVilla303",
  "id": 6902951,
  "avatar_url": "https://avatars.githubusercontent.com/u/6902951?v=3",
  "html_url": "https://github.com/GusVilla303",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 0,
  "C": 0,
  "CSS": 1,
  "PHP": 1,
  "Python": 1,
  "C++": 1,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 0,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 1
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "Hilaryous",
  "id": 5042071,
  "avatar_url": "https://avatars.githubusercontent.com/u/5042071?v=3",
  "html_url": "https://github.com/Hilaryous",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 1,
  "C": 1,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 0,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 0
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "HoracioChavez",
  "id": 3926939,
  "avatar_url": "https://avatars.githubusercontent.com/u/3926939?v=3",
  "html_url": "https://github.com/HoracioChavez",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 1,
  "Python": 0,
  "C++": 1,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 0,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "jcasimir",
  "id": 43102,
  "avatar_url": "https://avatars.githubusercontent.com/u/43102?v=3",
  "html_url": "https://github.com/jcasimir",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 0,
  "C": 0,
  "CSS": 0,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 0,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 1
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "marcgarreau",
  "id": 3621728,
  "avatar_url": "https://avatars.githubusercontent.com/u/3621728?v=3",
  "html_url": "https://github.com/marcgarreau",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 1,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 1
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "tanmdoan",
  "id": 7057689,
  "avatar_url": "https://avatars.githubusercontent.com/u/7057689?v=3",
  "html_url": "https://github.com/tanmdoan",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 1
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "timproctor",
  "id": 5150213,
  "avatar_url": "https://avatars.githubusercontent.com/u/5150213?v=3",
  "html_url": "https://github.com/timproctor",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 1,
  "CSS": 1,
  "PHP": 1,
  "Python": 0,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 1
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "tyrbo",
  "id": 2217533,
  "avatar_url": "https://avatars.githubusercontent.com/u/2217533?v=3",
  "html_url": "https://github.com/tyrbo",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 1,
  "C": 1,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 1
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "wfro",
  "id": 6454987,
  "avatar_url": "https://avatars.githubusercontent.com/u/6454987?v=3",
  "html_url": "https://github.com/wfro",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 0,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 0
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "worace",
  "id": 1227440,
  "avatar_url": "https://avatars.githubusercontent.com/u/1227440?v=3",
  "html_url": "https://github.com/worace",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 0,
  "PHP": 1,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 0,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 1
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "a6ftcruton",
  "id": 5419731,
  "avatar_url": "https://avatars.githubusercontent.com/u/5419731?v=3",
  "html_url": "https://github.com/a6ftcruton",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 1,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 1
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "awortham",
  "id": 6271986,
  "avatar_url": "https://avatars.githubusercontent.com/u/6271986?v=3",
  "html_url": "https://github.com/awortham",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 1,
  "C": 1,
  "CSS": 1,
  "PHP": 1,
  "Python": 0,
  "C++": 0,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 1,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 1
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "glenegbert",
  "id": 5980245,
  "avatar_url": "https://avatars.githubusercontent.com/u/5980245?v=3",
  "html_url": "https://github.com/glenegbert",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 1,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "ianderse",
  "id": 5242189,
  "avatar_url": "https://avatars.githubusercontent.com/u/5242189?v=3",
  "html_url": "https://github.com/ianderse",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 0,
  "C": 1,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 1,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "jcasimir",
  "id": 43102,
  "avatar_url": "https://avatars.githubusercontent.com/u/43102?v=3",
  "html_url": "https://github.com/jcasimir",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 0
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "kavitasa",
  "id": 1514862,
  "avatar_url": "https://avatars.githubusercontent.com/u/1514862?v=3",
  "html_url": "https://github.com/kavitasa",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 0,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 0
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "lukeaiken",
  "id": 3201898,
  "avatar_url": "https://avatars.githubusercontent.com/u/3201898?v=3",
  "html_url": "https://github.com/lukeaiken",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 1,
  "Python": 0,
  "C++": 0,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 1,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 1
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "rNavarrete",
  "id": 3431580,
  "avatar_url": "https://avatars.githubusercontent.com/u/3431580?v=3",
  "html_url": "https://github.com/rNavarrete",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 0,
  "CSS": 0,
  "PHP": 0,
  "Python": 1,
  "C++": 0,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 1,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "smbsimon",
  "id": 5553382,
  "avatar_url": "https://avatars.githubusercontent.com/u/5553382?v=3",
  "html_url": "https://github.com/smbsimon",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 0,
  "PHP": 1,
  "Python": 1,
  "C++": 1,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 0
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "worace",
  "id": 1227440,
  "avatar_url": "https://avatars.githubusercontent.com/u/1227440?v=3",
  "html_url": "https://github.com/worace",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 0,
  "PHP": 1,
  "Python": 0,
  "C++": 0,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 0,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 0
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "chandracarney",
  "id": 8561841,
  "avatar_url": "https://avatars.githubusercontent.com/u/8561841?v=3",
  "html_url": "https://github.com/chandracarney",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 0,
  "PHP": 1,
  "Python": 0,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 1,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "ChasevanHekken",
  "id": 5781795,
  "avatar_url": "https://avatars.githubusercontent.com/u/5781795?v=3",
  "html_url": "https://github.com/ChasevanHekken",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 1,
  "CSS": 0,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 0,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 0
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "Copywright",
  "id": 7808793,
  "avatar_url": "https://avatars.githubusercontent.com/u/7808793?v=3",
  "html_url": "https://github.com/Copywright",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 1,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 0,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 1
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "dalexj",
  "id": 2790993,
  "avatar_url": "https://avatars.githubusercontent.com/u/2790993?v=3",
  "html_url": "https://github.com/dalexj",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 0,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "dglunz",
  "id": 2965795,
  "avatar_url": "https://avatars.githubusercontent.com/u/2965795?v=3",
  "html_url": "https://github.com/dglunz",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "gregnar",
  "id": 8186136,
  "avatar_url": "https://avatars.githubusercontent.com/u/8186136?v=3",
  "html_url": "https://github.com/gregnar",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 0,
  "C": 0,
  "CSS": 0,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 1,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "katelane",
  "id": 3933878,
  "avatar_url": "https://avatars.githubusercontent.com/u/3933878?v=3",
  "html_url": "https://github.com/katelane",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 0,
  "CSS": 0,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 0,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "skuhlmann",
  "id": 6923345,
  "avatar_url": "https://avatars.githubusercontent.com/u/6923345?v=3",
  "html_url": "https://github.com/skuhlmann",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 0,
  "CSS": 1,
  "PHP": 1,
  "Python": 0,
  "C++": 1,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 0
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "Tmee",
  "id": 8226837,
  "avatar_url": "https://avatars.githubusercontent.com/u/8226837?v=3",
  "html_url": "https://github.com/Tmee",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 1,
  "C": 1,
  "CSS": 0,
  "PHP": 0,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "trayo",
  "id": 6809782,
  "avatar_url": "https://avatars.githubusercontent.com/u/6809782?v=3",
  "html_url": "https://github.com/trayo",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 0,
  "C": 0,
  "CSS": 1,
  "PHP": 1,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "VikiAnn",
  "id": 5874167,
  "avatar_url": "https://avatars.githubusercontent.com/u/5874167?v=3",
  "html_url": "https://github.com/VikiAnn",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 0,
  "C": 1,
  "CSS": 0,
  "PHP": 1,
  "Python": 0,
  "C++": 1,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 0,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "worace",
  "id": 1227440,
  "avatar_url": "https://avatars.githubusercontent.com/u/1227440?v=3",
  "html_url": "https://github.com/worace",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 1,
  "Python": 0,
  "C++": 0,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 0,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 0
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "zRouth",
  "id": 8505719,
  "avatar_url": "https://avatars.githubusercontent.com/u/8505719?v=3",
  "html_url": "https://github.com/zRouth",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 1,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 0,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "bhargavisatpathy",
  "id": 8531351,
  "avatar_url": "https://avatars.githubusercontent.com/u/8531351?v=3",
  "html_url": "https://github.com/bhargavisatpathy",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 0,
  "C": 1,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 0,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 1,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 1
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "bmrsny",
  "id": 8440504,
  "avatar_url": "https://avatars.githubusercontent.com/u/8440504?v=3",
  "html_url": "https://github.com/bmrsny",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 1,
  "C": 1,
  "CSS": 0,
  "PHP": 1,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 1
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "bryceholcomb",
  "id": 6202829,
  "avatar_url": "https://avatars.githubusercontent.com/u/6202829?v=3",
  "html_url": "https://github.com/bryceholcomb",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 1,
  "C": 1,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 0,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 1
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "cluhring",
  "id": 8466906,
  "avatar_url": "https://avatars.githubusercontent.com/u/8466906?v=3",
  "html_url": "https://github.com/cluhring",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 1,
  "Python": 1,
  "C++": 0,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 0,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 0
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "EmilyMB",
  "id": 8007635,
  "avatar_url": "https://avatars.githubusercontent.com/u/8007635?v=3",
  "html_url": "https://github.com/EmilyMB",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 1,
  "C": 0,
  "CSS": 0,
  "PHP": 1,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 0
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "Jwan622",
  "id": 6790201,
  "avatar_url": "https://avatars.githubusercontent.com/u/6790201?v=3",
  "html_url": "https://github.com/Jwan622",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 0,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "KristaANelson",
  "id": 8313881,
  "avatar_url": "https://avatars.githubusercontent.com/u/8313881?v=3",
  "html_url": "https://github.com/KristaANelson",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 1,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 0,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "larsonkonr",
  "id": 7245142,
  "avatar_url": "https://avatars.githubusercontent.com/u/7245142?v=3",
  "html_url": "https://github.com/larsonkonr",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 1,
  "C": 0,
  "CSS": 0,
  "PHP": 0,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 1,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 0
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "laurawhalin",
  "id": 8449527,
  "avatar_url": "https://avatars.githubusercontent.com/u/8449527?v=3",
  "html_url": "https://github.com/laurawhalin",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 0,
  "C": 1,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 1,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 0,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 0
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "Lydias303",
  "id": 8863407,
  "avatar_url": "https://avatars.githubusercontent.com/u/8863407?v=3",
  "html_url": "https://github.com/Lydias303",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 0,
  "C": 1,
  "CSS": 0,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 0,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 0
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "mikedao",
  "id": 3011748,
  "avatar_url": "https://avatars.githubusercontent.com/u/3011748?v=3",
  "html_url": "https://github.com/mikedao",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 0,
  "C": 1,
  "CSS": 0,
  "PHP": 1,
  "Python": 0,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 1,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "ndwhtlssthr",
  "id": 3827810,
  "avatar_url": "https://avatars.githubusercontent.com/u/3827810?v=3",
  "html_url": "https://github.com/ndwhtlssthr",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 0,
  "C": 1,
  "CSS": 0,
  "PHP": 1,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 1,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 1
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "oorion",
  "id": 869456,
  "avatar_url": "https://avatars.githubusercontent.com/u/869456?v=3",
  "html_url": "https://github.com/oorion",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 1,
  "C": 1,
  "CSS": 0,
  "PHP": 1,
  "Python": 0,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 1
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "rshea303",
  "id": 7894293,
  "avatar_url": "https://avatars.githubusercontent.com/u/7894293?v=3",
  "html_url": "https://github.com/rshea303",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 1,
  "CSS": 0,
  "PHP": 1,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 0,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "scottalexandra",
  "id": 8812335,
  "avatar_url": "https://avatars.githubusercontent.com/u/8812335?v=3",
  "html_url": "https://github.com/scottalexandra",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 1,
  "C": 0,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 1
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "scottcrawford03",
  "id": 8398867,
  "avatar_url": "https://avatars.githubusercontent.com/u/8398867?v=3",
  "html_url": "https://github.com/scottcrawford03",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 1,
  "C": 1,
  "CSS": 1,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 1,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "worace",
  "id": 1227440,
  "avatar_url": "https://avatars.githubusercontent.com/u/1227440?v=3",
  "html_url": "https://github.com/worace",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 0,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 0,
  "C++": 1,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 0,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 1
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "AllPurposeName",
  "id": 9127698,
  "avatar_url": "https://avatars.githubusercontent.com/u/9127698?v=3",
  "html_url": "https://github.com/AllPurposeName",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 1,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "DSynergy",
  "id": 7361182,
  "avatar_url": "https://avatars.githubusercontent.com/u/7361182?v=3",
  "html_url": "https://github.com/DSynergy",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 1,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 1
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "indiesquidge",
  "id": 3409645,
  "avatar_url": "https://avatars.githubusercontent.com/u/3409645?v=3",
  "html_url": "https://github.com/indiesquidge",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 1,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 1,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 0
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "jgu2160",
  "id": 5934106,
  "avatar_url": "https://avatars.githubusercontent.com/u/5934106?v=3",
  "html_url": "https://github.com/jgu2160",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 1,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 1
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "kpearson",
  "id": 3293289,
  "avatar_url": "https://avatars.githubusercontent.com/u/3293289?v=3",
  "html_url": "https://github.com/kpearson",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 0,
  "C": 0,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 0,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 1
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "kyrasteen",
  "id": 6415583,
  "avatar_url": "https://avatars.githubusercontent.com/u/6415583?v=3",
  "html_url": "https://github.com/kyrasteen",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 0,
  "C++": 1,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 0,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "SalesEngine was my glory days can we work on it again?"
},
  {
  "login": "mcshakes",
  "id": 8164007,
  "avatar_url": "https://avatars.githubusercontent.com/u/8164007?v=3",
  "html_url": "https://github.com/mcshakes",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 1,
  "C": 1,
  "CSS": 0,
  "PHP": 1,
  "Python": 0,
  "C++": 0,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 0,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "mirjoy",
  "id": 5142805,
  "avatar_url": "https://avatars.githubusercontent.com/u/5142805?v=3",
  "html_url": "https://github.com/mirjoy",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 0,
  "C": 0,
  "CSS": 1,
  "PHP": 1,
  "Python": 0,
  "C++": 1,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 1,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 0
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "neslom",
  "id": 8800860,
  "avatar_url": "https://avatars.githubusercontent.com/u/8800860?v=3",
  "html_url": "https://github.com/neslom",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 0,
  "C": 0,
  "CSS": 0,
  "PHP": 1,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 0
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "paulgrever",
  "id": 3664281,
  "avatar_url": "https://avatars.githubusercontent.com/u/3664281?v=3",
  "html_url": "https://github.com/paulgrever",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 0,
  "C": 1,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 1,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 0
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "treyx",
  "id": 9888146,
  "avatar_url": "https://avatars.githubusercontent.com/u/9888146?v=3",
  "html_url": "https://github.com/treyx",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 0,
  "PHP": 1,
  "Python": 1,
  "C++": 0,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "worace",
  "id": 1227440,
  "avatar_url": "https://avatars.githubusercontent.com/u/1227440?v=3",
  "html_url": "https://github.com/worace",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 1,
  "C": 1,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 0,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 0
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "xvalentino",
  "id": 8762410,
  "avatar_url": "https://avatars.githubusercontent.com/u/8762410?v=3",
  "html_url": "https://github.com/xvalentino",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 0,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 1
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "DaishaV",
  "id": 11197637,
  "avatar_url": "https://avatars.githubusercontent.com/u/11197637?v=3",
  "html_url": "https://github.com/DaishaV",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 0,
  "C": 0,
  "CSS": 1,
  "PHP": 1,
  "Python": 1,
  "C++": 1,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 1,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 0
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "jcasimir",
  "id": 43102,
  "avatar_url": "https://avatars.githubusercontent.com/u/43102?v=3",
  "html_url": "https://github.com/jcasimir",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 1,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 0,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 1
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "jmejia",
  "id": 73824,
  "avatar_url": "https://avatars.githubusercontent.com/u/73824?v=3",
  "html_url": "https://github.com/jmejia",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 1,
  "C": 0,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 1,
  "Perl": 0,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 0
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "JoshCheek",
  "id": 77495,
  "avatar_url": "https://avatars.githubusercontent.com/u/77495?v=3",
  "html_url": "https://github.com/JoshCheek",
  "languages": {
  "JavaScript": 1,
  "Java": 1,
  "Ruby": 1,
  "C": 1,
  "CSS": 0,
  "PHP": 1,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 0,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 1,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 0,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 1
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "marissamariesmith",
  "id": 12720982,
  "avatar_url": "https://avatars.githubusercontent.com/u/12720982?v=3",
  "html_url": "https://github.com/marissamariesmith",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 0,
  "C": 0,
  "CSS": 1,
  "PHP": 1,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 0,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 0,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 0
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "mikedao",
  "id": 3011748,
  "avatar_url": "https://avatars.githubusercontent.com/u/3011748?v=3",
  "html_url": "https://github.com/mikedao",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 1,
  "C": 1,
  "CSS": 0,
  "PHP": 1,
  "Python": 0,
  "C++": 0,
  "Objective-C": 1,
  "C#": 1,
  "Shell": 1,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 1,
  "Scala": 0,
  "VimL": 1,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 0
},
  "description": "Want to pair on my .vimrc? I got tired of Dvorak so i've been devising my own keyboard layout from scratch"
},
  {
  "login": "novohispano",
  "id": 1654034,
  "avatar_url": "https://avatars.githubusercontent.com/u/1654034?v=3",
  "html_url": "https://github.com/novohispano",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 1,
  "C": 1,
  "CSS": 1,
  "PHP": 0,
  "Python": 1,
  "C++": 1,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 0,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "raissashafer",
  "id": 8548182,
  "avatar_url": "https://avatars.githubusercontent.com/u/8548182?v=3",
  "html_url": "https://github.com/raissashafer",
  "languages": {
  "JavaScript": 1,
  "Java": 0,
  "Ruby": 0,
  "C": 1,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 0,
  "Go": 0,
  "Perl": 1,
  "Scala": 1,
  "VimL": 1,
  "Clojure": 1,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 1,
  "Swift": 1
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "rwarbelow",
  "id": 3311609,
  "avatar_url": "https://avatars.githubusercontent.com/u/3311609?v=3",
  "html_url": "https://github.com/rwarbelow",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 1,
  "C": 1,
  "CSS": 0,
  "PHP": 0,
  "Python": 1,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 0,
  "Go": 1,
  "Perl": 0,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 0,
  "Rust": 0,
  "Swift": 0
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
},
  {
  "login": "stevekinney",
  "id": 251000,
  "avatar_url": "https://avatars.githubusercontent.com/u/251000?v=3",
  "html_url": "https://github.com/stevekinney",
  "languages": {
  "JavaScript": 0,
  "Java": 0,
  "Ruby": 1,
  "C": 1,
  "CSS": 0,
  "PHP": 1,
  "Python": 0,
  "C++": 0,
  "Objective-C": 1,
  "C#": 0,
  "Shell": 0,
  "R": 0,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 1,
  "Scala": 1,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 0,
  "Erlang": 0,
  "Rust": 1,
  "Swift": 1
},
  "description": "i am so alone plz pair with me"
},
  {
  "login": "worace",
  "id": 1227440,
  "avatar_url": "https://avatars.githubusercontent.com/u/1227440?v=3",
  "html_url": "https://github.com/worace",
  "languages": {
  "JavaScript": 0,
  "Java": 1,
  "Ruby": 0,
  "C": 0,
  "CSS": 0,
  "PHP": 0,
  "Python": 0,
  "C++": 0,
  "Objective-C": 0,
  "C#": 1,
  "Shell": 1,
  "R": 1,
  "CoffeeScript": 1,
  "Go": 0,
  "Perl": 1,
  "Scala": 0,
  "VimL": 0,
  "Clojure": 0,
  "Haskell": 1,
  "Erlang": 1,
  "Rust": 0,
  "Swift": 0
},
  "description": "would love to get your help on my new startup; it's in stealth mode so we can only use 1-character variable names, but it will be fun"
}
].each do |user_json|
  User.find_or_create_with_oauth(user_json)
end
